export const UPLOAD_FILE = 'UPLOAD_FILE';
export const ADD_TRACK = 'ADD_TRACK';
export const ADJUST_SETTINGS = 'ADJUST_SETTINGS';
export const ADJUST_GLOBAL_SETTINGS = 'ADJUST_GLOBAL_SETTINGS';
export const FOCUS_WINDOW = 'FOCUS_WINDOW';