export const UPLOAD_FILE = 'UPLOAD_FILE';
export const SELECT_COLUMN = 'SELECT_COLUMN';
export const ADJUST_SETTINGS = 'ADJUST_SETTINGS';
export const ADJUST_GLOBAL_SETTINGS = 'ADJUST_GLOBAL_SETTINGS';